using System;
using System.Collections.Generic;

namespace Brudex.CodeFirst
{
    class CollectionsFactory
    {
        private Random random;
        public string GetRandomSeed(string columnName, Random rnd)
        {
            random = rnd;
           
            ArrayToUse arrayToUse = GetArrayToUse(columnName.ToLower());
            switch (arrayToUse)
            {
                case ArrayToUse.FirstNames:
                    return RandomValue(firstnames);

                case ArrayToUse.LastNames:
                    return RandomValue(lastnames);
                    break; 

                case ArrayToUse.Products:
                    return RandomValue(randomproducts);
                    break; 

                case ArrayToUse.FullNames:
                    return RandomValue(fullNames);
                    break;
                
                case ArrayToUse.Titles:
                    return RandomValue(titles);
                    break;
                
                case ArrayToUse.OtherNames:
                    return RandomValue(othernames);
                    break;
                
                case ArrayToUse.Comments:
                    return RandomValue(comments);
                    break;
                    
                default:
                    return RandomValue(comments);

            }


        }

        private ArrayToUse GetArrayToUse(string columnName)
        {
            ArrayToUse atu = ArrayToUse.Comments;
            
            if (Array.IndexOf(firstNameLabels,columnName)>=0)
            {
                atu = ArrayToUse.FirstNames;
            }
            else if (Array.IndexOf(lastNameLabels,columnName)>=0)
            {
                atu = ArrayToUse.LastNames;
            }
             
            else if (Array.IndexOf(nameLabels,columnName)>=0)
            {
                atu = ArrayToUse.FullNames;
            }
            else if (Array.IndexOf(descriptionNameLabels,columnName)>=0)
            {
                atu = ArrayToUse.Comments;
            }
            else if (Array.IndexOf(productNameLabels,columnName)>=0)
            {
                atu = ArrayToUse.FirstNames;
            }
            else if (Array.IndexOf(titleNameLabels,columnName)>=0)
            {
                atu = ArrayToUse.Titles;
            }
            else
            {
                if (columnName.Contains("name"))
                {
                    atu = ArrayToUse.FullNames;

                }
                else
                {
                    ///choose between names and products
                    int ch = random.Next(1, 2);
                    if (ch == 1)
                    {
                        atu = ArrayToUse.FullNames;
                    }
                    else
                    {
                        atu=ArrayToUse.Products;
                    }
                }
            }

            

            return atu;

        }

        enum ArrayToUse
        {
            FirstNames,LastNames,FullNames, Products, Titles, OtherNames, Comments
        }

        private string RandomValue(string[] arrayToUse)
        {
            int index = random.Next(0, arrayToUse.Length-1);
            return arrayToUse[index];
        }

        private string[] nameLabels = new string[]
            {
                "name","fullname","names"
            };

        private string[] firstNameLabels = new string[]
            {
                "fname","firstname","firsname","fn","firstnames"
            };

        private string[] lastNameLabels = new string[]
            {
                "lname","lastname","ltname","ln","lastnames","lasname"
            };

        private string[] productNameLabels = new string[]
            {
                "products","product","orders","label","categories","category","productName"
            };

        private string[] descriptionNameLabels = new string[]
            {
                "description","comment","comments","label",
            };
        
        private string[] titleNameLabels = new string[]
            {
                "title","label","heading","header","movies","movie","titles","video","videos","labels"
            };


        private static string[] randomproducts = new string[]
            {
                "Android Homme",
                "White Mountaineering",
                "Skora Running",
                "Alejandro Ingelmo",
                "APL (Athletic Propulsion Labs)",
                "Lotek",
                "Terrem",
                "Lakai",
                "SeaVees",
                "Pointer Footwear",
                "IPATH",
                "Creative Recreation",
                " Newton Running",
                "Alife",
                "Generic Surplus",
                "Supra Footwear",
                "Common Projects",
                "Blackspot",
                "Under Armour",
                "Etnies",
                "Superga",
                "Gourmet",
                "Visvim",
                "Clae",
                "New Balance",
                "Nike",
                "Adidas",
                "Converse",
                "Vans",
                "Reebok",
                "Jordan",
                "Puma",
                "Toyota",
                "Ford",
                "Honda",
                "Chevrolet",
                "Tesla",
                "Subaru",
                "Mercedes-Benz",
                "Volvo",
                "Cadillac",
                "BMW",
                "Buick",
                "GMC",
                "Audi",
                "Nissan",
                "Smart",
                "Dodge",
                "Lexus",
                "Volkswagen",
                "Hyundai",
                "Kia",
                "Nokia 1100",
                "Nokia 1110",
                "Nokia 1200",
                "Nokia 5230",
                "Nokia 3210",
                "Nokia 6600",
                "Nokia 2600 (2610/2626/2630)",
                "Motorola RAZR V3",
                "Nokia 1600 (1650/1661)",
                "Motorola C200",
                "Motorola V220",
                "Motorola V195",
                "Motorola PEBL U6",
                "Motorola SLVR L6",
                "Motorola SLVR L7",
                "Motorola KRZR K1",
                "Nokia 3310 (3330)",
                "Nokia 1208 (1209)",
                "Nokia 6010 (6020/6030)",
                "Nokia 5130 (5220/5310)",
                "Nokia 3100 (3120)",
                "Nokia 6230 (6233)",
                "Motorola StarTAC",
                "Alcatel One Touch Mini OT-708",
                "BenQ-Siemens S68",
                "HTC Thunderbolt",
                "LG Chocolate",
                "LG Optimus One",
                "Apple iPhone 4S",
                "Samsung Star",
                "Samsung E250",
                "Samsung Galaxy S",
                "Samsung Galaxy S II",
                "Samsung Galaxy S III",
                "Samsung Galaxy S4",
                "Samsung Galaxy Note II",
                "RIM BlackBerry Pearl",
                "Samsung S8300 Tocco Ultra",
                "Siemens M30 (M35i)",
                "Siemens A50",
                "Sony Ericsson K300",
                "Sony Ericsson J300",
                "Sony Ericsson K750",
                "Sony Ericsson K310",
                "Sony Ericsson W810",
                "Apple iPhone 3GS",
                "Nokia 6270 (6280)",
                "Nokia 5200 (5300)",
                "Nokia E71",
                "Nokia 6120",
                "Nokia 3510",
                "Nokia 6100",
                "Nokia 6610",
                "Nokia 1680",

            };

        private static string[] comments = new string[]
            {
                "Michael Abrash – Popularized Mode X for DOS. This allows for faster video refresh and square pixels.",
                "Scott Adams – one of earliest developers of CP/M and DOS games",
                "Leonard Adleman – co-creator of RSA algorithm (the A in the name stands for Adleman), coined the term computer virus"
                ,
                "Alfred Aho – co-creator of AWK (the A in the name stands for Aho), and main author of famous Dragon book"
                ,
                "JJ Allaire – creator of ColdFusion Application Server, ColdFusion Markup Language",
                "Andrei Alexandrescu – author, expert C++, D languages",
                "Paul Allen – Altair BASIC, Applesoft BASIC, co-founded Microsoft",
                "Eric Allman – sendmail, syslog",
                "Marc Andreessen – co-creator of Mosaic, co-founder of Netscape",
                "Jeremy Ashkenas – creator of the CoffeeScript programming language and Backbone.js",
                "Bill Atkinson – QuickDraw, HyperCard",
                "John Backus – FORTRAN, BNF",
                "Richard Bartle – MUD, with Roy Trubshaw, creator of MUDs",
                "Brian Behlendorf – Apache",
                "Kent Beck – Created Extreme Programming and co-creator of JUnit",
                "Donald Becker – Linux Ethernet drivers, Beowulf clustering",
                "Doug Bell – Dungeon Master series of video games",
                "Fabrice Bellard – Creator of FFmpeg open codec library, QEMU virtualization tools",
                "Tim Berners-Lee – inventor of World Wide Web",
                "Daniel J. Bernstein – djbdns, qmail",
                "Sabeer Bhatia – Co-founded the Hotmail email service",
                "Eric Bina – co-creator of Mosaic web browser",
                "Marc Blank – co-creator of Zork",
                "Joshua Bloch – core Java language designer, lead the Java collections framework project",
                "Grady Booch – Co-creator of Unified Modeling Language",
                "Bert Bos – author of Argo web browser, co-author of Cascading Style Sheets",
                "Stephen Richard Bourne – Creator of Bourne shell",
                "David Bradley – coder on the IBM PC project team who wrote the Control-Alt-Delete keyboard handler, embedded in all PC-compatible BIOSes"
                ,
                "Andrew Braybrook – video games Paradroid and Uridium",
                "Larry Breed – co-developer of APL 360",
                "Jack E. Bresenham – creator of Bresenham's line algorithm",
                "Dan Bricklin – co-creator of VisiCalc, the first personal spreadsheet program",
                "Walter Bright – Digital Mars, First C++ compiler, author of D (programming language).",
                "Richard Brodie – Microsoft Word",
                "Andries Brouwer – Hack, former maintainer of man pager man(1), Linux kernel hacker",
                "Danielle Bunten Berry (Dani Bunten) – M.U.L.E., multiplayer video game and other noted video games",
                "Dries Buytaert – Creator of Drupal",
                "Steve Capps – co-creator of Macintosh and Newton",
                "John D. Carmack – first person shooters Doom, Quake",
                "Vinton Cerf – TCP/IP, NCP",
                "Ward Christensen – Wrote the first BBS (Bulletin Board System) system CBBS",
                "Edgar F. Codd – principal architect of the relational model",
                "Bram Cohen – BitTorrent protocol design and implementation",
                "Alain Colmerauer – Prolog",
                "Alan Cooper – Visual Basic",
                "Alan Cox – co-developer of Linux kernel",
                "Brad Cox – Objective-C",
                "Mike Cowlishaw – REXX and NetRexx, LEXX editor, image processing, decimal arithmetic packages",
                "Mark Crispin – creator of IMAP, author of UW-IMAP, one of reference implementations of IMAP4",
                "Ward Cunningham – creator of Wiki concept",
                "William Crowther – Colossal Cave Adventure",
                "Dave Cutler – architect of VMS, Windows NT",
                "Ole-Johan Dahl – co-creator of SIMULA",
                "James Duncan Davidson – creator of Tomcat, now part of Jakarta Project",
                "L. Peter Deutsch – Ghostscript, Assembler for PDP-1, XDS-940 timesharing system, QED original co-author"
                ,
                "Edsger Dijkstra – contributions to ALGOL, Dijkstra's algorithm, Goto Statement Considered Harmful",
                "Matt Dillon – programmer of various software including DICE and DragonflyBSD",
                "Jack Dorsey – creator of Twitter",
                "Martin Dougiamas – creator and lead developer of Moodle",
                "Adam Dunkels – author of Contiki operating system, the lwIP and uIP embedded TCP/IP stacks, inventor of protothreads"
                ,
                "Les Earnest – author of finger program",
                "Brendan Eich – creator of JavaScript",
                "Larry Ellison – co-creator of Oracle database, co-founder of Oracle Corporation",
                "Marc Ewing – creator of Red Hat Linux",
                "Dan Farmer – Creator of COPS and Security Administrator Tool for Analyzing Networks (SATAN) Security Scanners"
                ,
                "Stuart Feldman – creator of make, author of Fortran 77 compiler, part of original group that created Unix"
                ,
                "David Filo – co-creator of Yahoo!",
                "Brad Fitzpatrick – creator of memcached, Livejournal and OpenID",
                "Andrew Fluegelman – author PC-Talk communications software; considered a co-creator of shareware",
                "Brian Fox – creator of Bash, Readline, GNU Finger, Meta-HTML",
                "Martin Fowler – Creator of Dependency Injection pattern of software engineering, a form of Inversion of control"
                ,
                "Jim Fruchterman – founder of Arkenstone (now part of Freedom Scientific) and Benetech, created scanners for blind people"
                ,
                "Elon Gasper – co-founded Bright Star Technology, patented realistic facial movements for in-game speech. HyperAnimator, Alphabet Blocks, etc."
                ,
                "Bill Gates – Altair BASIC, co-founded Microsoft",
                "Jim Gettys – X Window System, HTTP/1.1, One Laptop per Child, Bufferbloat",
                "Steve Gibson – creator of SpinRite",
                "John Gilmore – GDB",
                "Adele Goldberg – co-creator of Smalltalk",
                "Ryan C. Gordon (a.k.a. Icculus) – Lokigames, ioquake3, MojoSetup, etc.",
                "James Gosling – Java, Gosling Emacs, NeWS",
                "Bill Gosper – Macsyma, Lisp machine, hashlife, helped Donald Knuth on Vol.2 of The Art of Computer Programming (Semi-numerical algorithms)"
                ,
                "Andrew Gower – RuneScape Classic, RuneScape, co-founded Jagex",
                "Paul Gower – RuneScape Classic, RuneScape, co-founded Jagex",
                "Paul Graham – Yahoo! Store, On Lisp, ANSI Common Lisp",
                "John Graham-Cumming – author of POPFile, a Bayesian filter-based e-mail classifier",
                "Ralph Griswold – co-creator of SNOBOL, creator of Icon (programming language)",
                "Richard Greenblatt – Lisp machine, Incompatible Timesharing System, MacHack",
                "Neil J. Gunther — author of PDQ (Pretty Damn Quick) performance modeling program",
                "Scott Guthrie, (a.k.a. ScottGu) – ASP.NET Creator",
                "Andi Gutmans – co-creator of PHP programming language",
                "Jim Hall – started the FreeDOS project",
                "David Heinemeier Hansson – created the Ruby on Rails framework for developing web applications.",
                "David Albert Huffman – created the Huffman Code compression algorithm.",
                "Rebecca Heineman – Author of Bard's Tale III: Thief of Fate and Dragon Wars.",
                "Anders Hejlsberg – Turbo Pascal, Borland Delphi,C#,TypeScript",
                "Ted Henter – founder of Henter-Joyce (now part of Freedom Scientific) creator of Jaws, screen reader software for blind people"
                ,
                "Andy Hertzfeld – co-creator of Macintosh, co-founder of General Magic, co-founder of Eazel",
                "Rich Hickey – creator of Clojure language",
                "D. Richard Hipp – creator of SQLite",
                "C. A. R. Hoare – first implementation of quicksort, ALGOL 60 compiler, Communicating sequential processes"
                ,
                "James Holmes – Committer on Struts project, create of Struts Console",
                "Grace Hopper – Harvard Mark I computer, FLOW-MATIC, COBOL",
                "Dave Hyatt – co-author of Mozilla Firefox",
                "Miguel de Icaza – GNOME project leader, initiator of Mono project",
                "Roberto Ierusalimschy – Lua leading architect",
                "Dan Ingalls – co-creator of Smalltalk and Bitblt",
                "Geir Ivarsøy – co-creator of Opera web browser",
                "Ken Iverson – APL, J",
                "Toru Iwatani – creator of Pac-Man",
                "Bo Jangeborg – Sinclair ZX Spectrum games",
                "Paul Jardetzky – author of server program for the first webcam",
                "Lynne Jolitz – 386BSD",
                "William Jolitz – 386BSD",
                "Stephen C. Johnson – yacc",
                "Bill Joy – BSD, csh, vi, co-founder of Sun Microsystems",
                "Robert K. Jung – creator of ARJ",
                "Poul-Henning Kamp – MD5 password hash algorithm, FreeBSD GEOM and GBDE, part of the UFS2, FreeBSD Jails, malloc and the Beerware license"
                ,
                "Mitch Kapor – Lotus 1-2-3, founded Lotus Development Corporation",
                "Phil Katz – creator of ZIP file format, author of PKZIP",
                "Alan Kay – Smalltalk, Dynabook, Object-oriented programming, Squeak",
                "Mel Kaye – a real programmer[1]",
                "John Kemeny – co-creator of BASIC",
                "Stan Kelly-Bootle – Manchester Mark 1, The Devil's DP Dictionary",
                "Brian Kernighan – co-creator of AWK (the K in the name stands for Kernighan), author of ditroff text-formatting tool"
                ,
                "Gary Kildall – CP/M",
                "Tom Knight – Incompatible Timesharing System",
                "Jim Knopf – aka Jim Button, author PC-File flatfile database; considered a co-creator of shareware",
                "Donald E. Knuth – TeX, CWEB, Metafont, The Art of Computer Programming, Concrete Mathematics",
                "Andrew R. Koenig – (co-)author of books on C and C++ and former Project Editor of the ISO/ANSI standards committee for C++"
                ,
                "Andre LaMothe- LaMothe is the creator of the XGameStation,one of the world's first video game console development kits"
                ,
                "Tom Lane – primary author of libjpeg, major developer of PostgreSQL",
                "Leslie Lamport – LaTeX",
                "Butler Lampson – QED original co-author",
                "Sam Lantinga – creator of SDL",
                "Dick Lathwell – co-developer of APL\\360",
                "Chris Lattner – primary author of LLVM project",
                "Samuel J Leffler – BSD, FlexFAX, libtiff, FreeBSD Wireless Device Drivers",
                "Rasmus Lerdorf – original creator of PHP",
                "Michael Lesk – Lex",
                "Gordon Letwin – Architect of OS/2, author of HPFS file system",
                "Rockford Lhotka – Creator of the CSLA framework",
                "Håkon Wium Lie – co-author of Cascading Style Sheets",
                "Robert Love – Linux kernel developer",
                "Ada Lovelace – First programmer (of Charles Babbages' Analytical Engine)",
                "Al Lowe – creator of Leisure Suit Larry series",
                "Raphael Manfredi – contributions to Perl, software architect and maintainer of gtk-gnutella",
                "Khaled Mardam-Bey – Creator of mIRC (Internet Relay Chat Client)",
                "Yukihiro Matsumoto – Ruby",
                "John McCarthy – Lisp",
                "Craig McClanahan – original author of Jakarta Struts, architect of Tomcat Catalina servlet container",
                "Daniel D. McCracken – professor at City College and author of Guide to Algol Programming, Guide to Cobol Programming, Guide to Fortran Programming (1957)"
                ,
                "Douglas McIlroy – pipes and filters, concept of software componentry, Unix tools (spell, diff, sort, join, graph, speak, tr, etc.)"
                ,
                "Shawn McKenzie – AutoTheme",
                "Marshall Kirk McKusick – BSD, work on FFS, implementor of soft updates",
                "Bertrand Meyer – Eiffel, Object-oriented Software Construction, Design by contract",
                "Scott Meyers – author, software consultant, C++ expert",
                "Bob Miner – co-creator of Oracle database, co-founder of Oracle Corporation",
                "Jeff Minter – Psychedelic, and often llama-related video games",
                "Lou Montulli – creator of Lynx browser, cookies, the blink tag, server push and client pull, HTTP proxying, HTTP over SSL, browser integration with animated GIFs, founding member of HTML working group at W3C"
                ,
                "Bram Moolenaar – author of text-editor Vim",
                "David Moon – Maclisp, ZetaLisp",
                "Charles H. Moore – creator of Forth language",
                "Roger Moore – co-developer of APL\\360, creator of IPSANET, co-founder of I.P. Sharp Associates",
                "Matt Mullenweg – Author of WordPress",
                "Boyd Munro — Australian developer of GRASP, owner of SDI, one of the earliest software development companies"
                ,
                "Mike Muuss – author of ping, network tool to detect hosts",
                "Patrick Naughton – early Java designer, xlock, HotJava",
                "Peter Naur – Backus-Naur form, ALGOL 60",
                "Fredrik Neij – co-creator of The Pirate Bay",
                "Graham Nelson – creator of Inform authoring system for Interactive fiction",
                "Peter Norton – programmer of the famous utility program, Norton Utilities",
                "Kristen Nygaard – SIMULA",
                "Ed Oates – co-creator of Oracle database, co-founder of Oracle Corporation",
                "Martin Odersky – Scala",
                "Jarkko Oikarinen – creator of Internet Relay Chat (IRC)",
                "Andrew and Philip Oliver, The Oliver Twins – Many Sinclair ZX Spectrum games including Dizzy",
                "John Ousterhout – creator of Tcl/Tk",
                "Onel de Guzman – A Filipino Programmer who created the ILOVEYOU virus on May 4, 2000.",
                 
                "Larry Page – Co-founder of Google, Inc.",
                "Alexey Pajitnov – creator of game Tetris on Electronica 60",
                "Seymour Papert – Logo (programming language)",
                "Tim Paterson – author of 86-DOS (QDOS)",
                "Markus Persson – Creator of Minecraft",
                "Petr Mitrichev – considered one of the best algorithmists in the world today",
                "Jeffrey Peterson – key free and open source software architect, creator of Quepasa",
                "Charles Petzold – author of many Microsoft Windows programming books",
                "Rob Pike – Wrote first bitmapped window system for Unix, co-creator of UTF-8 character encoding, author of text editor sam and programming environment acme, main author of Plan 9 and Inferno operating systems, and co-author of the Go (programming language)"
                ,
                "Kent Pitman – technical contributor to the ANSI Common Lisp standard",
                 
                "Theo de Raadt – Founding member of NetBSD, founder of OpenBSD and OpenSSH",
                "Jef Raskin – started the Macintosh project in Apple Computer, designed Canon Cat computer, developed The Humane Environment program"
                ,
                "Eric Raymond – Open Source movement, author of fetchmail",
                "Hans Reiser – Creator of ReiserFS file system.",
                "John Resig – Creator and lead developer of jQuery JavaScript library",
                "Craig Reynolds – Creator of boids computer graphics simulation",
                "Dennis Ritchie – C, Unix, Plan 9 from Bell Labs, Inferno",
                "Ron Rivest – co-creator of RSA algorithm (the R in the name stands for Rivest). Creator of RC4 and MD5."
                ,
                "John Romero – first person shooters Doom, Quake",
                "Blake Ross – co-author of Mozilla Firefox",
                "Guido van Rossum – Python",
                "Jeff Rulifson – Lead programmer on the NLS project",
                "Rusty Russell – Creator of iptables for linux",
                "Steve Russell – First Lisp interpreter; original Spacewar! graphic video game.",
                "Mark Russinovich – Sysinternals.com, Filemon, Regmon, Process Explorer, TCPView and RootkitRevealer",
                "Bob Sabiston – Rotoshop, interpolating rotoscope animation software",
                "Muni Sakya – Nepalese software",
                "Carl Sassenrath – Amiga, REBOL",
                "Chris Sawyer – Developer of Roller Coaster Tycoon and the Transport Tycoon series",
                "Bill Schelter – GNU Maxima, GNU Common Lisp",
                "Randal L. Schwartz – Just another Perl hacker",
                "Adi Shamir – co-creator of RSA algorithm (the S in the name stands for Shamir)",
                "Mike Shaver – Founding member of Mozilla Organization",
                "Cliff Shaw – IPL, the first AI language",
                "Zed Shaw – Wrote the Mongrel Web Server, for Ruby web applications.",
                "Emily Short – prolific writer of Interactive fiction and co-developer of Inform version 7",
                "Jacek Sieka – Developer of DC++ an open-source, peer-to-peer file-sharing client",
                "Ken Silverman – creator of Duke Nukem 3D's graphics engine",
                "Charles Simonyi – Hungarian notation, Bravo (the first WYSIWYG text editor), Microsoft Word.",
                "Colin Simpson – developer of CircuitLogix simulation software",
                "Rich Skrenta – co-founder of DMOZ",
                "Matthew Smith – Sinclair ZX Spectrum games, including Manic Miner and Jet Set Willy",
                "Henry Spencer – C News, Regex",
                "Joel Spolsky – Co-founder of Fog Creek Software and Stack Overflow",
                "Quentin Stafford-Fraser – author of original VNC viewer, first Windows VNC server, client program for the first webcam"
                ,
                "Richard Stallman – Emacs, GCC, GDB, founder and pioneer of GNU Project, terminal-independent I/O pioneer on ITS, Lisp machine manual"
                ,
                "Guy Steele – Common Lisp, Scheme, Java",
                "Alexander Stepanov – Creator of Standard Template Library",
                "Christopher Strachey — draughts playing program",
                "Ludvig Strigeus – Creator of uTorrent, OpenTTD, ScummVM and the technology behind Spotify",
                "Bjarne Stroustrup – Creator of C++",
                "Zeev Suraski – co-creator of PHP language",
                "Gerald Jay Sussman – Scheme",
                "Herb Sutter – Chair of the ISO C++ standards committee and C++ expert.",
                "Gottfrid Svartholm – co-creator of The Pirate Bay",
                "Tim Sweeney – The Unreal engine, UnrealScript, ZZT",
                "Andrew Tanenbaum – Minix",
                "Audrey \"Autrijus\" Tang – designer of Pugs",
                "Simon Tatham – NASM, PuTTY",
                "Larry Tesler – the PUB markup language, the Smalltalk code browser, debugger and object inspector, and (with Tim Mott) the Gypsy word processor"
                ,
                "Jon Stephenson von Tetzchner – co-creator of Opera web browser",
                "Avie Tevanian – author of Mach kernel",
                "Ken Thompson – main designer and author of Unix, Plan 9 and Inferno operating systems, B and Bon languages (precursors of C), creator of UTF-8 character encoding, introduced regular expressions in QED and co-author of the Go (programming language)"
                ,
                "Michael Tiemann – G++, GCC",
                "Linus Torvalds – original author and current maintainer of Linux kernel and creator of Git, a source code management system"
                ,
                "Andrew Tridgell – Samba, Rsync",
                "Roy Trubshaw – MUD – together with Richard Bartle, creator of MUDs",
                "Bob Truel – co-founder of DMOZ",
                "Alan Turing",
                "Wietse Venema – Postfix, Security Administrator Tool for Analyzing Networks (SATAN), TCP Wrapper",
                "Pat Villani – original author of the FreeDOS/DOS-C kernel, maintainer of a defunct Linux for Windows 9x distribution",
                "Paul Vixie – BIND, Cron",
                "Patrick Volkerding – Original author and the current maintainer of Slackware Linux Distribution",
                "Larry Wall – Warp (1980s space-war game), rn, patch, Perl",
                "Bob Wallace – author PC-Write word processor; considered a co-creator of shareware",
                "John Walker – co-founder of Autodesk",
                "John Warnock – creator of PostScript",
                "Joseph Weizenbaum – creator of ELIZA",
                "Robert Watson – FreeBSD network stack parallelism, TrustedBSD project and OpenBSM",
                "Pei-Yuan Wei – author of Viola, one of earliest graphical browsers",
                "Peter J. Weinberger – co-creator of AWK (the W in the name stands for Weinberger)",
                "Jim Weirich – creator of Rake, Builder, and Ruby Gems for Ruby, and a popular teacher and conference speaker."
                ,
                "Andrew Welch – author of Maelstrom, Snapz Pro; founder of Ambrosia Software",
                "David Wheeler – co-creator of subroutine; designer of WAKE; co-designer of Tiny Encryption Algorithm, XTEA, Burrows-Wheeler transform."
                ,
                "Arthur Whitney – A+, K",
                "why the lucky stiff – creator of libraries and writing for Ruby, as well as a quirky and popular guide to learning programming"
                ,
                "Bruce Wilcox – creator of Computer Go, programmed NEMESIS Go Master.",
                "Evan Williams Creator and co-founder of Twitter",
                "Roberta and Ken Williams – Sierra Entertainment, King's Quest, graphic adventure game",
                "Sophie Wilson – Designer of instruction set for Acorn RISC Machine, author of BBC BASIC.",
                "Dave Winer – developed XML-RPC, Frontier scripting language",
                "Niklaus Wirth – Pascal, Modula-2, Oberon",
                "Stephen Wolfram – creator of Mathematica",
                "Don Woods – INTERCAL, Colossal Cave Adventure",
                "Steve Wozniak – Breakout, Apple Integer BASIC, co-founder of Apple Inc.",
                "Will Wright – Created the Sim City series and co-founded Maxis",
                "Jerry Yang – co-creator of Yahoo!",
                "Victor Yngve – author of first string processing language, COMIT",
                "Jamie Zawinski – Lucid Emacs, Netscape, Mozilla, XScreenSaver",
                "Philip Zimmermann – creator of encryption software PGP, the ZRTP protocol, and Zfone",
                "Mark Zuckerberg – Creator of Facebook"
            };

        private static string[] fullNames = new string[]
            {
                "Michael Abrash",
                "Scott Adams",
                "Leonard Adleman",
                "Alfred Aho",
                "JJ Allaire",
                "Andrei Alexandrescu",
                "Paul Allen",
                "Eric Allman",
                "Marc Andreessen",
                "Jeremy Ashkenas",
                "Bill Atkinson",
                "John Backus",
                "Richard Bartle",
                "Brian Behlendorf",
                "Kent Beck",
                "Donald Becker",
                "Doug Bell",
                "Fabrice Bellard",
                "Tim Berners-Lee",
                "Daniel J. Bernstein",
                "Sabeer Bhatia",
                "Eric Bina",
                "Marc Blank",
                "Joshua Bloch",
                "Grady Booch",
                "Bert Bos",
                "Stephen Richard Bourne",
                "David Bradley",
                "Andrew Braybrook",
                "Larry Breed",
                "Jack E. Bresenham",
                "Dan Bricklin",
                "Walter Bright",
                "Richard Brodie",
                "Andries Brouwer",
                "Danielle Bunten Berry",
                "Dries Buytaert",
                "Steve Capps",
                "John D. Carmack",
                "Vinton Cerf",
                "Ward Christensen",
                "Edgar F. Codd",
                "Bram Cohen",
                "Alain Colmerauer",
                "Alan Cooper",
                "Alan Cox",
                "Brad Cox",
                "Mike Cowlishaw",
                "Mark Crispin",
                "Ward Cunningham",
                "William Crowther",
                "Dave Cutler",
                "Ole-Johan Dahl",
                "James Duncan Davidson",
                "L. Peter Deutsch",
                "Edsger Dijkstra",
                "Matt Dillon",
                "Jack Dorsey",
                "Martin Dougiamas",
                "Adam Dunkels",
                "Les Earnest",
                "Brendan Eich",
                "Larry Ellison",
                "Marc Ewing",
                "Dan Farmer",
                "Stuart Feldman",
                "David Filo",
                "Brad Fitzpatrick",
                "Andrew Fluegelman",
                "Brian Fox",
                "Martin Fowler",
                "Jim Fruchterman",
                "Elon Gasper",
                "Bill Gates",
                "Jim Gettys",
                "Steve Gibson",
                "John Gilmore",
                "Adele Goldberg",
                "Ryan C. Gordon",
                "James Gosling",
                "Bill Gosper",
                "Andrew Gower",
                "Paul Gower",
                "Paul Graham",
                "John Graham-Cumming",
                "Ralph Griswold",
                "Richard Greenblatt",
                "Neil J. Gunther",
                "Scott Guthrie",
                "Andi Gutmans",
                "Jim Hall",
                "David Heinemeier Hansson",
                "David Albert Huffman",
                "Rebecca Heineman",
                "Anders Hejlsberg",
                "Ted Henter",
                "Andy Hertzfeld",
                "Rich Hickey",
                "D. Richard Hipp",
                "C. A. R. Hoare",
                "James Holmes",
                "Grace Hopper",
                "Dave Hyatt",
                "Miguel de Icaza",
                "Roberto Ierusalimschy",
                "Dan Ingalls",
                "Geir Ivarsøy",
                "Ken Iverson",
                "Toru Iwatani",
                "Bo Jangeborg",
                "Paul Jardetzky",
                "Lynne Jolitz",
                "William Jolitz",
                "Stephen C. Johnson",
                "Bill Joy",
                "Robert K. Jung",
                "Poul-Henning Kamp",
                "Mitch Kapor",
                "Phil Katz",
                "Alan Kay",
                "Mel Kaye",
                "John Kemeny",
                "Stan Kelly-Bootle",
                "Brian Kernighan",
                "Gary Kildall",
                "Tom Knight",
                "Jim Knopf",
                "Donald E. Knuth",
                "Andrew R. Koenig",
                "Andre LaMothe",
                "Tom Lane",
                "Leslie Lamport",
                "Butler Lampson",
                "Sam Lantinga",
                "Dick Lathwell",
                "Chris Lattner",
                "Samuel J Leffler",
                "Rasmus Lerdorf",
                "Michael Lesk",
                "Gordon Letwin",
                "Rockford Lhotka",
                "Håkon Wium Lie",
                "Robert Love",
                "Ada Lovelace",
                "Al Lowe",
                "Raphael Manfredi",
                "Khaled Mardam-Bey",
                "Yukihiro Matsumoto",
                "John McCarthy",
                "Craig McClanahan",
                "Daniel D. McCracken",
                "Douglas McIlroy",
                "Shawn McKenzie",
                "Marshall Kirk McKusick",
                "Bertrand Meyer",
                "Scott Meyers",
                "Bob Miner",
                "Jeff Minter",
                "Lou Montulli",
                "Bram Moolenaar",
                "David Moon",
                "Charles H. Moore",
                "Roger Moore",
                "Matt Mullenweg",
                "Boyd Munro",
                "Mike Muuss",
                "Patrick Naughton",
                "Peter Naur",
                "Fredrik Neij",
                "Graham Nelson",
                "Peter Norton",
                "Kristen Nygaard",
                "Ed Oates",
                "Martin Odersky",
                "Jarkko Oikarinen",
                "Philip Oliver",
                "Andrew Oliver",
                "John Ousterhout",
                "Onel de Guzman",
                "Larry Page",
                "Alexey Pajitnov",
                "Seymour Papert",
                "Tim Paterson",
                "Markus Persson",
                "Petr Mitrichev",
                "Jeffrey Peterson",
                "Charles Petzold",
                "Rob Pike",
                "Kent Pitman",
                "Theo de Raadt",
                "Jef Raskin",
                "Eric Raymond",
                "Hans Reiser",
                "John Resig",
                "Craig Reynolds",
                "Dennis Ritchie",
                "Ron Rivest",
                "John Romero",
                "Blake Ross",
                "Guido van Rossum",
                "Jeff Rulifson",
                "Rusty Russell",
                "Steve Russell",
                "Mark Russinovich",
                "Bob Sabiston",
                "Muni Sakya",
                "Carl Sassenrath",
                "Chris Sawyer",
                "Bill Schelter",
                "Randal L. Schwartz",
                "Adi Shamir",
                "Mike Shaver",
                "Cliff Shaw",
                "Zed Shaw",
                "Emily Short",
                "Jacek Sieka",
                "Ken Silverman",
                "Charles Simonyi",
                "Colin Simpson",
                "Rich Skrenta",
                "Matthew Smith",
                "Henry Spencer",
                "Joel Spolsky",
                "Quentin Stafford-Fraser",
                "Richard Stallman",
                "Guy Steele",
                "Alexander Stepanov",
                "Christopher Strachey",
                "Ludvig Strigeus",
                "Bjarne Stroustrup",
                "Zeev Suraski",
                "Gerald Jay Sussman",
                "Herb Sutter",
                "Gottfrid Svartholm",
                "Tim Sweeney",
                "Andrew Tanenbaum",
                "Audrey \"Autrijus\" Tang",
                "Simon Tatham",
                "Larry Tesler",
                "Jon Stephenson von Tetzchner",
                "Avie Tevanian",
                "Ken Thompson",
                "Michael Tiemann",
                "Linus Torvalds",
                "Andrew Tridgell",
                "Roy Trubshaw",
                "Bob Truel",
                "Alan Turing",
                "Wietse Venema",
                "Pat Villani",
                "Paul Vixie",
                "Patrick Volkerding",
                "Larry Wall",
                "Bob Wallace",
                "John Walker",
                "John Warnock",
                "Joseph Weizenbaum",
                "Robert Watson",
                "Pei-Yuan Wei",
                "Peter J. Weinberger",
                "Jim Weirich",
                "Andrew Welch",
                "David Wheeler",
                "Arthur Whitney",
                "why the lucky stiff",
                "Bruce Wilcox",
                "Evan Williams",
                "Roberta and Ken Williams",
                "Sophie Wilson",
                "Dave Winer",
                "Niklaus Wirth",
                "Stephen Wolfram",
                "Don Woods",
                "Steve Wozniak",
                "Will Wright",
                "Jerry Yang",
                "Victor Yngve",
                "Jamie Zawinski",
                "Philip Zimmermann"

            };


        private string[] lastnames = new string[]
            {
                "Abrash",
                "Adams",
                "Adleman",
                "Aho",
                "Allaire",
                "Alexandrescu",
                "Allen",
                "Allman",
                "Andreessen",
                "Ashkenas",
                "Atkinson",
                "Backus",
                "Bartle",
                "Behlendorf",
                "Beck",
                "Becker",
                "Bell",
                "Bellard",
                "Berners-Lee",
                "Bernstein",
                "Bhatia",
                "Bina",
                "Blank",
                "Bloch",
                "Booch",
                "Bos",
                "Bourne",
                "Bradley",
                "Braybrook",
                "Breed",
                "Bresenham",
                "Bricklin",
                "Bright",
                "Brodie",
                "Brouwer",
                "Berry",
                "Buytaert",
                "Capps",
                "Carmack",
                "Cerf",
                "Christensen",
                "Codd",
                "Cohen",
                "Colmerauer",
                "Cooper",
                "Cox",
                "Cox",
                "Cowlishaw",
                "Crispin",
                "Cunningham",
                "Crowther",
                "Cutler",
                "Dahl",
                "Davidson",
                "Deutsch",
                "Dijkstra",
                "Dillon",
                "Dorsey",
                "Dougiamas",
                "Dunkels",
                "Earnest",
                "Eich",
                "Ellison",
                "Ewing",
                "Farmer",
                "Feldman",
                "Filo",
                "Fitzpatrick",
                "Fluegelman",
                "Fox",
                "Fowler",
                "Fruchterman",
                "Gasper",
                "Gates",
                "Gettys",
                "Gibson",
                "Gilmore",
                "Goldberg",
                "Gordon",
                "Gosling",
                "Gosper",
                "Gower",
                "Gower",
                "Graham",
                "Graham-Cumming",
                "Griswold",
                "Greenblatt",
                "Gunther",
                "Guthrie",
                "Gutmans",
                "Hall",
                "Hansson",
                "Huffman",
                "Heineman",
                "Hejlsberg",
                "Henter",
                "Hertzfeld",
                "Hickey",
                "Hipp",
                "Hoare",
                "Holmes",
                "Hopper",
                "Hyatt",
                "Icaza",
                "Ierusalimschy",
                "Ingalls",
                "Ivarsøy",
                "Iverson",
                "Iwatani",
                "Jangeborg",
                "Jardetzky",
                "Jolitz",
                "Jolitz",
                "Johnson",
                "Joy",
                "Jung",
                "Kamp",
                "Kapor",
                "Katz",
                "Kay",
                "Kaye",
                "Kemeny",
                "Kelly-Bootle",
                "Kernighan",
                "Kildall",
                "Knight",
                "Knopf",
                "Knuth",
                "Koenig",
                "LaMothe",
                "Lane",
                "Lamport",
                "Lampson",
                "Lantinga",
                "Lathwell",
                "Lattner",
                "Leffler",
                "Lerdorf",
                "Lesk",
                "Letwin",
                "Lhotka",
                "Lie",
                "Love",
                "Lovelace",
                "Lowe",
                "Manfredi",
                "Mardam-Bey",
                "Matsumoto",
                "McCarthy",
                "McClanahan",
                "McCracken",
                "McIlroy",
                "McKenzie",
                "McKusick",
                "Meyer",
                "Meyers",
                "Miner",
                "Minter",
                "Montulli",
                "Moolenaar",
                "Moon",
                "Moore",
                "Moore",
                "Mullenweg",
                "Munro",
                "Muuss",
                "Naughton",
                "Naur",
                "Neij",
                "Nelson",
                "Norton",
                "Nygaard",
                "Oates",
                "Odersky",
                "Oikarinen",
                "Oliver",
                "Oliver",
                "Ousterhout",
                "Guzman",
                "Page",
                "Pajitnov",
                "Papert",
                "Paterson",
                "Persson",
                "Mitrichev",
                "Peterson",
                "Petzold",
                "Pike",
                "Pitman",
                "de Raadt",
                "Raskin",
                "Raymond",
                "Reiser",
                "Resig",
                "Reynolds",
                "Ritchie",
                "Rivest",
                "Romero",
                "Ross",
                "van Rossum",
                "Rulifson",
                "Russell",
                "Russell",
                "Russinovich",
                "Sabiston",
                "Sakya",
                "Sassenrath",
                "Sawyer",
                "Schelter",
                "Schwartz",
                "Shamir",
                "Shaver",
                "Shaw",
                "Shaw",
                "Short",
                "Sieka",
                "Silverman",
                "Simonyi",
                "Simpson",
                "Skrenta",
                "Smith",
                "Spencer",
                "Spolsky",
                "Stafford-Fraser",
                "Stallman",
                "Steele",
                "Stepanov",
                "Strachey",
                "Strigeus",
                "Stroustrup",
                "Suraski",
                "Sussman",
                "Sutter",
                "Svartholm",
                "Sweeney",
                "Tanenbaum",
                "Tang",
                "Tatham",
                "Tesler",
                "von Tetzchner",
                "Tevanian",
                "Thompson",
                "Tiemann",
                "Torvalds",
                "Tridgell",
                "Trubshaw",
                "Truel",
                "Turing",
                "Venema",
                "Villani",
                "Vixie",
                "Volkerding",
                "Wall",
                "Wallace",
                "Walker",
                "Warnock",
                "Weizenbaum",
                "Watson",
                "Wei",
                "Weinberger",
                "Weirich",
                "Welch",
                "Wheeler",
                "Whitney",
                " stiff",
                "Wilcox",
                "Williams",
                "Williams",
                "Wilson",
                "Winer",
                "Wirth",
                "Wolfram",
                "Woods",
                "Wozniak",
                "Wright",
                "Yang",
                "Yngve",
                "Zawinski",
                "Zimmermann",
                "Zuckerberg"
            };

    

        private string[] firstnames = new string[]
            {
                "Michael",
                "Scott",
                "Leonard",
                "Alfred",
                "JJ",
                "Andrei",
                "Paul",
                "Eric",
                "Marc",
                "Jeremy",
                "Bill",
                "John",
                "Richard",
                "Brian",
                "Kent",
                "Donald",
                "Doug",
                "Fabrice",
                "Tim",
                "Daniel",
                "Sabeer",
                "Eric",
                "Marc",
                "Joshua",
                "Grady",
                "Bert",
                "Stephen",
                "David",
                "Andrew",
                "Larry",
                "Jack",
                "Dan",
                "Walter",
                "Richard",
                "Andries",
                "Danielle",
                "Dries",
                "Steve",
                "John",
                "Vinton",
                "Ward",
                "Edgar",
                "Bram",
                "Alain",
                "Alan",
                "Alan",
                "Brad",
                "Mike",
                "Mark",
                "Ward",
                "William",
                "Dave",
                "Ole-Johan",
                "James",
                "Peter",
                "Edsger",
                "Matt",
                "Jack",
                "Martin",
                "Adam",
                "Les",
                "Brendan",
                "Larry",
                "Marc",
                "Dan",
                "Stuart",
                "David",
                "Brad",
                "Andrew",
                "Brian",
                "Martin",
                "Jim",
                "Elon",
                "Bill",
                "Jim",
                "Steve",
                "John",
                "Adele",
                "Ryan",
                "James",
                "Bill",
                "Andrew",
                "Paul",
                "Paul",
                "John",
                "Ralph",
                "Richard",
                "Neil",
                "Scott",
                "Andi",
                "Jim",
                "Heinemeier",
                "David",
                "Rebecca",
                "Anders",
                "Ted",
                "Andy",
                "Rich",
                "Richard",
                "C. A. R.",
                "James",
                "Grace",
                "Dave",
                "Miguel",
                "Roberto",
                "Dan",
                "Geir",
                "Ken",
                "Toru",
                "Bo",
                "Paul",
                "Lynne",
                "William",
                "Stephen",
                "Bill",
                "Robert",
                "Poul-Henning",
                "Mitch",
                "Phil",
                "Alan",
                "Mel",
                "John",
                "Stan",
                "Brian",
                "Gary",
                "Tom",
                "Jim",
                "Donald",
                "Andrew",
                "Andre",
                "Tom",
                "Leslie",
                "Butler",
                "Sam",
                "Dick",
                "Chris",
                "Samuel",
                "Rasmus",
                "Michael",
                "Gordon",
                "Rockford",
                "Håkon",
                "Robert",
                "Ada",
                "Al",
                "Raphael",
                "Khaled",
                "Yukihiro",
                "John",
                "Craig",
                "Daniel",
                "Douglas",
                "Shawn",
                "Marshall",
                "Bertrand",
                "Scott",
                "Bob",
                "Jeff",
                "Lou",
                "Bram",
                "David",
                "Charles",
                "Roger",
                "Matt",
                "Boyd",
                "Mike",
                "Patrick",
                "Peter",
                "Fredrik",
                "Graham",
                "Peter",
                "Kristen",
                "Ed",
                "Martin",
                "Jarkko",
                "Philip",
                "Andrew",
                "John",
                "Onel",
                "Larry",
                "Alexey",
                "Seymour",
                "Tim",
                "Markus",
                "Petr",
                "Jeffrey",
                "Charles",
                "Rob",
                "Kent",
                "Theo",
                "Jef",
                "Eric",
                "Hans",
                "John",
                "Craig",
                "Dennis",
                "Ron",
                "John",
                "Blake",
                "Guido",
                "Jeff",
                "Rusty",
                "Steve",
                "Mark",
                "Bob",
                "Muni",
                "Carl",
                "Chris",
                "Bill",
                "Randal",
                "Adi",
                "Mike",
                "Cliff",
                "Zed",
                "Emily",
                "Jacek",
                "Ken",
                "Charles",
                "Colin",
                "Rich",
                "Matthew",
                "Henry",
                "Joel",
                "Quentin",
                "Richard",
                "Guy",
                "Alexander",
                "Christopher",
                "Ludvig",
                "Bjarne",
                "Zeev",
                "Gerald",
                "Herb",
                "Gottfrid",
                "Tim",
                "Andrew",
                "Audrey",
                "Simon",
                "Larry",
                "Jon",
                "Avie",
                "Ken",
                "Michael",
                "Linus",
                "Andrew",
                "Roy",
                "Bob",
                "Alan",
                "Wietse",
                "Pat",
                "Paul",
                "Patrick",
                "Larry",
                "Bob",
                "John",
                "John",
                "Joseph",
                "Robert",
                "Pei-Yuan",
                "Peter",
                "Jim",
                "Andrew",
                "David",
                "Arthur",
                "why the",
                "Bruce",
                "Evan",
                "Roberta and Ken",
                "Sophie",
                "Dave",
                "Niklaus",
                "Stephen",
                "Don",
                "Steve",
                "Will",
                "Jerry",
                "Victor",
                "Jamie",
                "Philip",
                "Mark"
            };

        private string[] titles = new string[]
            {
                "Avatar",
                "Titanic",
                "Marvel's The Avengers",
                "Harry Potter and the Deathly Hallows – Part 2",
                "Iron Man 3",
                "Frozen film currently playing",
                "Transformers: Dark of the Moon",
                "The Lord of the Rings: The Return of the King",
                "Skyfall",
                "The Dark Knight Rises",
                "Pirates of the Caribbean: Dead Man's Chest",
                "Toy Story 3",
                "Pirates of the Caribbean: On Stranger Tides",
                "Jurassic Park",
                "Star Wars Episode I: The Phantom Menace",
                "Alice in Wonderland",
                "The Hobbit: An Unexpected Journey",
                "The Dark Knight",
                "The Lion King",
                "Harry Potter and the Philosopher's Stone",
                "Despicable Me 2",
                "Pirates of the Caribbean: At World's End",
                "Harry Potter and the Deathly Hallows – Part 1",
                "The Hobbit: The Desolation of Smaug",
                "Harry Potter and the Order of the Phoenix",
                "Finding Nemo",
                "Harry Potter and the Half-Blood Prince",
                "The Lord of the Rings: The Two Towers",
                "Shrek 2",
                "Harry Potter and the Goblet of Fire",
                "Spider-Man 3",
                "Ice Age: Dawn of the Dinosaurs",
                "Harry Potter and the Chamber of Secrets",
                "Ice Age: Continental Drift",
                "The Lord of the Rings: The Fellowship of the Ring",
                "The Hunger Games: Catching Fire",
                "Star Wars Episode III: Revenge of the Sith",
                "Transformers: Revenge of the Fallen",
                "The Twilight Saga: Breaking Dawn – Part 2",
                "Inception",
                "Spider-Man",
                "Independence Day",
                "Shrek the Third",
                "Harry Potter and the Prisoner of Azkaban",
                "E.T. the Extra-Terrestrial",
                "Fast & Furious 6",
                "Indiana Jones and the Kingdom of the Crystal Skull",
                "Spider-Man 2",
                "Star Wars",
                "2012",
            };

     
        private string[] othernames = new  string[]
        {

            "Albert"	,
            "Autrijus"	,
            "Bunten"	,
            "C."	,
            "C."	,
            "D."	,
            "D."	,
            "D."	,
            "David"	,
            "de"	,
            "de"	,
            "Duncan"	,
            "E."	,
            "E."	,
            "F."	,
            "H."	,
            "J"	,
            "J."	,
            "J."	,
            "J."	,
            "Jay"	,
            "K."	,
            "Kirk"	,
            "L."	,
            "L."	,
            "lucky"	,
            "R."	,
            "Richard"	,
            "Stephenson"	,
            "Wium"	,

        };



    }
}